package com.hearopilot.app.domain.model

/**
 * Represents an insight or suggestion generated by the LLM based on transcribed text.
 *
 * Each insight belongs to a specific transcription session, ensuring LLM context
 * remains isolated between different recording sessions.
 *
 * @property id Unique identifier for this insight
 * @property sessionId ID of the session this insight belongs to
 * @property title AI-generated brief title for this insight (for SIMPLE_LISTENING, SHORT_MEETING, LONG_MEETING)
 * @property content The LLM-generated insight text (summary, analysis, or translation)
 * @property tasks Extracted action items/tasks (JSON array) for meeting modes, null otherwise
 * @property timestamp Unix timestamp (milliseconds) when this insight was generated
 * @property sourceSegmentIds List of TranscriptionSegment IDs that contributed to this insight
 */
data class LlmInsight(
    val id: String,
    val sessionId: String,
    val title: String? = null,
    val content: String,
    val tasks: String? = null, // JSON array of tasks: [{"task": "...", "priority": "high|medium|low"}]
    val timestamp: Long,
    val sourceSegmentIds: List<String>
)
