import json, pathlib

data = {
  "nodes": [
    {"id": "build_gradle_root", "label": "Root Build Gradle", "file_type": "code", "source_file": "build.gradle.kts", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "settings_gradle", "label": "Settings Gradle", "file_type": "code", "source_file": "settings.gradle.kts", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "app_build_gradle", "label": "App Build Gradle", "file_type": "code", "source_file": "app/build.gradle.kts", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "meetmindapplication", "label": "MeetMindApplication", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/MeetMindApplication.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "model_cloudbadgestate", "label": "CloudBadgeState Enum", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/CloudBadgeState.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "model_cloudinferencerequest", "label": "CloudInferenceRequest Data Class", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/CloudInferenceRequest.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "model_cloudprovider", "label": "CloudProvider Enum", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/CloudProvider.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "model_cloudproviderconfig", "label": "CloudProviderConfig Data Class", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/CloudProviderConfig.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "model_fallbackreason", "label": "FallbackReason Enum", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/FallbackReason.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "model_inferenceevent", "label": "InferenceEvent Sealed Class", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/InferenceEvent.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "model_inferencemode", "label": "InferenceMode Enum", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/InferenceMode.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "model_sessionmode", "label": "SessionMode Enum", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/SessionMode.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "model_suggestion", "label": "Suggestion Data Class", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/Suggestion.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "di_appcontainer", "label": "AppContainer DI", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/di/AppContainer.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "inference_claudeinferenceclient", "label": "ClaudeInferenceClient", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/ClaudeInferenceClient.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "inference_clock", "label": "Clock Interface", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/Clock.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "inference_systemclock", "label": "SystemClock", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/Clock.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "inference_cloudbadgecontroller", "label": "CloudBadgeController", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudBadgeController.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "inference_cloudinferenceengine", "label": "CloudInferenceEngine", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudInferenceEngine.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "inference_cloudkeyvalidationservice", "label": "CloudKeyValidationService", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudKeyValidationService.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "inference_validationresult", "label": "ValidationResult Enum", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudKeyValidationService.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None},
    {"id": "inference_cloudstreamingprovider", "label": "CloudStreamingProvider Interface", "file_type": "code", "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudStreamingProvider.kt", "source_location": None, "source_url": None, "captured_at": None, "author": None, "contributor": None}
  ],
  "edges": [
    {"source": "meetmindapplication", "target": "di_appcontainer", "relation": "calls", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/MeetMindApplication.kt", "source_location": "line 15", "weight": 1.0},
    {"source": "di_appcontainer", "target": "inference_claudeinferenceclient", "relation": "calls", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/di/AppContainer.kt", "source_location": "line 47", "weight": 1.0},
    {"source": "di_appcontainer", "target": "inference_cloudinferenceengine", "relation": "calls", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/di/AppContainer.kt", "source_location": "line 40", "weight": 1.0},
    {"source": "di_appcontainer", "target": "inference_cloudkeyvalidationservice", "relation": "calls", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/di/AppContainer.kt", "source_location": "line 32", "weight": 1.0},
    {"source": "inference_claudeinferenceclient", "target": "inference_cloudstreamingprovider", "relation": "implements", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/ClaudeInferenceClient.kt", "source_location": "line 31", "weight": 1.0},
    {"source": "inference_claudeinferenceclient", "target": "model_cloudinferencerequest", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/ClaudeInferenceClient.kt", "source_location": "line 43", "weight": 1.0},
    {"source": "inference_claudeinferenceclient", "target": "model_inferenceevent", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/ClaudeInferenceClient.kt", "source_location": "line 73", "weight": 1.0},
    {"source": "inference_claudeinferenceclient", "target": "model_cloudprovider", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/ClaudeInferenceClient.kt", "source_location": "line 83", "weight": 1.0},
    {"source": "inference_claudeinferenceclient", "target": "inference_cloudkeyvalidationservice", "relation": "calls", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/ClaudeInferenceClient.kt", "source_location": "line 93", "weight": 1.0},
    {"source": "inference_systemclock", "target": "inference_clock", "relation": "implements", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/Clock.kt", "source_location": "line 16", "weight": 1.0},
    {"source": "inference_cloudbadgecontroller", "target": "model_cloudbadgestate", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudBadgeController.kt", "source_location": "line 31", "weight": 1.0},
    {"source": "inference_cloudbadgecontroller", "target": "model_cloudprovider", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudBadgeController.kt", "source_location": "line 28", "weight": 1.0},
    {"source": "inference_cloudbadgecontroller", "target": "model_inferenceevent", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudBadgeController.kt", "source_location": "line 56", "weight": 1.0},
    {"source": "inference_cloudinferenceengine", "target": "model_cloudinferencerequest", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudInferenceEngine.kt", "source_location": "line 66", "weight": 1.0},
    {"source": "inference_cloudinferenceengine", "target": "model_cloudprovider", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudInferenceEngine.kt", "source_location": "line 107", "weight": 1.0},
    {"source": "inference_cloudinferenceengine", "target": "model_fallbackreason", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudInferenceEngine.kt", "source_location": "line 76", "weight": 1.0},
    {"source": "inference_cloudinferenceengine", "target": "model_inferenceevent", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudInferenceEngine.kt", "source_location": "line 76", "weight": 1.0},
    {"source": "inference_cloudinferenceengine", "target": "inference_cloudstreamingprovider", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudInferenceEngine.kt", "source_location": "line 42", "weight": 1.0},
    {"source": "inference_cloudinferenceengine", "target": "inference_clock", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudInferenceEngine.kt", "source_location": "line 44", "weight": 1.0},
    {"source": "inference_cloudinferenceengine", "target": "inference_systemclock", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudInferenceEngine.kt", "source_location": "line 44", "weight": 1.0},
    {"source": "inference_cloudkeyvalidationservice", "target": "model_cloudprovider", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudKeyValidationService.kt", "source_location": "line 37", "weight": 1.0},
    {"source": "inference_cloudkeyvalidationservice", "target": "inference_validationresult", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudKeyValidationService.kt", "source_location": "line 16", "weight": 1.0},
    {"source": "inference_cloudstreamingprovider", "target": "model_cloudinferencerequest", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudStreamingProvider.kt", "source_location": "line 18", "weight": 1.0},
    {"source": "inference_cloudstreamingprovider", "target": "model_inferenceevent", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudStreamingProvider.kt", "source_location": "line 18", "weight": 1.0},
    {"source": "inference_cloudstreamingprovider", "target": "inference_validationresult", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudStreamingProvider.kt", "source_location": "line 19", "weight": 1.0},
    {"source": "model_cloudinferencerequest", "target": "model_cloudprovider", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/CloudInferenceRequest.kt", "source_location": "line 29", "weight": 1.0},
    {"source": "model_cloudinferencerequest", "target": "model_sessionmode", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/CloudInferenceRequest.kt", "source_location": "line 33", "weight": 1.0},
    {"source": "model_cloudproviderconfig", "target": "model_cloudprovider", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/CloudProviderConfig.kt", "source_location": "line 13", "weight": 1.0},
    {"source": "model_inferenceevent", "target": "model_cloudprovider", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/InferenceEvent.kt", "source_location": "line 24", "weight": 1.0},
    {"source": "model_inferenceevent", "target": "model_fallbackreason", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/InferenceEvent.kt", "source_location": "line 31", "weight": 1.0},
    {"source": "model_suggestion", "target": "model_inferencemode", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/Suggestion.kt", "source_location": "line 23", "weight": 1.0},
    {"source": "model_suggestion", "target": "model_cloudprovider", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/Suggestion.kt", "source_location": "line 28", "weight": 1.0},
    {"source": "model_suggestion", "target": "model_fallbackreason", "relation": "references", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/Suggestion.kt", "source_location": "line 31", "weight": 1.0},
    {"source": "model_suggestion", "target": "model_cloudinferencerequest", "relation": "shares_data_with", "confidence": "INFERRED", "confidence_score": 0.9, "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/Suggestion.kt", "source_location": "line 29", "weight": 1.0},
    {"source": "inference_cloudinferenceengine", "target": "inference_claudeinferenceclient", "relation": "calls", "confidence": "EXTRACTED", "confidence_score": 1.0, "source_file": "app/src/main/kotlin/com/meetmind/assistant/di/AppContainer.kt", "source_location": "line 47", "weight": 1.0},
    {"source": "model_inferencemode", "target": "model_cloudbadgestate", "relation": "semantically_similar_to", "confidence": "INFERRED", "confidence_score": 0.7, "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/InferenceMode.kt", "source_location": None, "weight": 0.7},
    {"source": "model_fallbackreason", "target": "model_inferenceevent", "relation": "conceptually_related_to", "confidence": "INFERRED", "confidence_score": 0.9, "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/FallbackReason.kt", "source_location": None, "weight": 0.9},
    {"source": "inference_cloudbadgecontroller", "target": "inference_cloudinferenceengine", "relation": "conceptually_related_to", "confidence": "INFERRED", "confidence_score": 0.85, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudBadgeController.kt", "source_location": None, "weight": 0.85}
  ],
  "hyperedges": [
    {"id": "cloud_inference_pipeline", "label": "Cloud Inference Pipeline", "nodes": ["inference_cloudinferenceengine", "inference_cloudstreamingprovider", "model_inferenceevent"], "relation": "participate_in", "confidence": "EXTRACTED", "confidence_score": 0.95, "source_file": "app/src/main/kotlin/com/meetmind/assistant/inference/CloudInferenceEngine.kt"},
    {"id": "cloud_provider_config_security", "label": "Cloud Provider Config and Security", "nodes": ["model_cloudproviderconfig", "model_cloudprovider", "inference_cloudkeyvalidationservice"], "relation": "participate_in", "confidence": "INFERRED", "confidence_score": 0.85, "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/CloudProviderConfig.kt"},
    {"id": "suggestion_inference_metadata", "label": "Suggestion Inference Metadata", "nodes": ["model_suggestion", "model_inferencemode", "model_fallbackreason"], "relation": "form", "confidence": "EXTRACTED", "confidence_score": 0.92, "source_file": "app/src/main/kotlin/com/meetmind/assistant/data/model/Suggestion.kt"}
  ],
  "input_tokens": 0,
  "output_tokens": 0
}

out = pathlib.Path("F:/Git/meetmind-assistant/graphify-out/.graphify_chunk_01.json")
out.write_text(json.dumps(data, separators=(",", ":")))
print("Written", out)
